### ISSUE TITLE
 installation package 😅

### ISSUE THREAD

**Issue by infernoshoot** [mika-f/blender-drag-and-drop#1]
The installation package cannot be downloaded

**Comment by mika-f** [comment]
Sorry, this add-on is currently working in my environment, but I have not been able to confirm that it works in other testers' environments and am investigating, so I am not providing an installation package.

**Comment by mika-f** [comment]
I have made some modifications and confirmed that it works in the tester's environment.  
Therefore, I'll distribute the installation package after making some improvements.
I hope you can wait until then.

**Comment by infernoshoot** [comment]
Okay, thanks 👌

**Comment by mika-f** [comment]
Hi, I released the first installation package to [Releases](https://github.com/mika-f/blender-drag-and-drop/releases/tag/v0.1.0).
There are some differences from regular Blender add-ons, so please refer to the user documentation.

How to Install: https://docs.natsuneko.moe/en-US/drag-and-drop-support/installation/
How to Use: https://docs.natsuneko.moe/en-US/drag-and-drop-support/how-to-use/

**Comment by infernoshoot** [comment]
> 你好，我發布了第一個安裝包到[Releases](https://github.com/mika-f/blender-drag-and-drop/releases/tag/v0.1.0)。 與常規 Blender 插件有一些不同，請參閱用戶文檔。
> 
> 如何安裝：https://docs.natsuneko.moe/en-US/drag-and-drop-support/installation/如何使用：[https://docs.natsuneko.moe/en-US/drag-and-刪除支持/如何使用/](https://docs.natsuneko.moe/en-US/drag-and-drop-support/how-to-use/)

Hello, when you create a new file, you have to re-open the listening in order to import
Is there a way to fix it?😊

**Comment by mika-f** [comment]
I'll try to fix it this weekend......; please wait a little longer.

**Comment by mika-f** [comment]
I've reproduced the problem, I'll try to fix it.

**Comment by mika-f** [comment]
I've fixed the bug on creating a new state on Blender.
Due to Blender's restrictions, it is necessary to start the listener again, but it no longer shows an invalid state.

Release: https://github.com/mika-f/blender-drag-and-drop/releases/tag/v0.1.1

**Comment by infernoshoot** [comment]
> 我已经修复了在 Blender 上创建新状态的错误。 由于 Blender 的限制，需要重新启动监听器，但它不再显示无效状态。
> 
> 发布：[https ://github.com/mika-f/blender-drag-and-drop/releases/tag/v0.1.1](https://github.com/mika-f/blender-drag-and-drop/releases/tag/v0.1.1)

Thank you
Can you make the launcher remember the path?😊

**Comment by mika-f** [comment]
Hi, I released a [v0.2.0](https://github.com/mika-f/blender-drag-and-drop/releases/tag/v0.2.0) that includes creating Windows shortcuts.
This is different from launcher-ui remembering the path, but you can do the same.
