### ISSUE TITLE
Interferes with some asset browser files

### ISSUE THREAD

**Issue by crizzpy** [mika-f/blender-drag-and-drop#23]
The add-on is great, but unfortunately it is interfering with the built-in asset browser of Blender, for me anyway. I cannot drag and drop the following assets without having Blender crash:
- World Materials
- Node Groups

Is there a way to check that the filetype is blender-internal and gets skipped?

To recreate the issue, just open a blend file and have an asset saved (in the built-in asset browser) as a world texture or node group, with Drag and Drop enabled. When those filetypes are dragged into the viewport, the program crashes instantly. I disabled the Drag and Drop addon in preferences, and this behaviour disappeared entirely.

**Comment by mika-f** [comment]
Thanks for your feedback. Can you please ptovide the version of Blender, the version of add-on, and details steps to reproduce the problem?

**Comment by mika-f** [comment]
Hi, I maybe fixed crash bug in Release v2.5.0. Are you try it?

**Comment by crizzpy** [comment]
Looks like it is working perfectly now. Thanks for your hard work, I love the add-on!
