### ISSUE TITLE
[Bug]: Image plane is not created

### ISSUE THREAD

**Issue by mephisrussia** [mika-f/blender-drag-and-drop#29]
### What happened?

Dragging and dropping images into the viewport does not work. The image plane is not created.

When you disable the plugin, everything works.

Blender 3.5.0

### Add-on Version

2.5.0

**Comment by mika-f** [comment]
Thank you for your bug report.
I will respond as mush as possible during the holidays.

**Comment by mika-f** [comment]
This bug fix will be included in the next v2.6.0 release!
Sorry for the late reply.
