### ISSUE TITLE
Obj and STL importers use older, slower commands

### ISSUE THREAD

**Issue by pfalkingham** [mika-f/blender-drag-and-drop#38]
Blender 3.4/3.5 saw obj and stl importers updated to be significantly faster.  Looks like this is still using the legacy importers?

**Comment by mika-f** [comment]
Yes. I'm currently using the old importer. However, I think it is better to use the new improvement importers, so I'll use the new one if available on add-on loaded version of Blender!

**Comment by mika-f** [comment]
Resolved in https://github.com/mika-f/blender-drag-and-drop/pull/37.
