### ISSUE TITLE
[Feature Request]: Support to Blender 3.6.0

### ISSUE THREAD

**Issue by mika-f** [mika-f/blender-drag-and-drop#42]
### What do you want?

Blender 3.6.0 is released.

https://download.blender.org/release/Blender3.6/

**Comment by 3020** [comment]
Please update to 3.6. Currently doesn´t work out of the box... Seems to install correctly (after exposing the contained folder with the plugin/s proper .zip), but drag and drop prints: "...current value (etc) matches no enum in ´Event´", and also the 3D panel shows, but with an empty listener section.

**Comment by mika-f** [comment]
If all goes well, Blender 3.6.0 compatible version will be released within a few days. This will be releases as v2.7.0, instead of v3.0.0.

**Comment by mika-f** [comment]
This PR has been released as v2.7.1.
