### ISSUE TITLE
[Feature Request]: Support Blender 3.6.1

### ISSUE THREAD

**Issue by Dangry98** [mika-f/blender-drag-and-drop#47]
### What do you want?

The add-on is currently not supported in Blender 3.6.1.

Blender 3.6.1 had some very important bug and crash fixes. So, if this add-on would be updated to support 3.6.1, it would be much appreciated.

**Comment by roy-shuvashish** [comment]
Hi, thanks a lot for the addon. Is it possible to drag multiple stl files into blender using this or only one at a time?

**Comment by mika-f** [comment]
Currently, it is not possible to import multiple files at the same time.
See #22 for progress tracking.
