### ISSUE TITLE
[Bug]: Can't drag and drop import models

### ISSUE THREAD

**Issue by Sostay** [mika-f/blender-drag-and-drop#52]
### What happened?

I downloaded and installed the plugin and enabled it, but I still can't drag and drop to import, just like I did before I installed the plugin.
I downloaded the portable version of the latest version (3.6.1) from the official website, and I wonder if it differs from the installer version

### Add-on Version

2.8.0

### Blender versions

3.6.1

**Comment by survivalizeed** [comment]
same here

**Comment by nehalllem** [comment]
same. it doesnt work. nothing happens.
last steam blender version 3.6.1
addon version 2.8.0

**Comment by mika-f** [comment]
I will investigate this issue over the weekend as I have free time.

**Comment by mika-f** [comment]
Please check the following things:

1. What variants are you using? (Blender or Blender for Artists, or another variant)
1. What formats are you try to import file(s)? (e.g. FBX)
1. What SHA-256 HASH of `DragAndDropSupport-v2.8.0.zip`?

**Comment by Sostay** [comment]
> Please check the following things:
> 
> 1. What variants are you using? (Blender or Blender for Artists, or another variant)您使用什么变体？ （搅拌机或艺术家搅拌机，或其他变体）
> 2. What formats are you try to import file(s)? (e.g. FBX)
> 3. What operating systems are you using? (e.g. Windows 11 x64)
> 4. What SHA-256 HASH of `DragAndDropSupport-v2.8.0.zip`? (if possible)

I just tried it again and the plugin suddenly works fine. But it really wasn't working before, I don't know why ......😂😂😂

**Comment by mika-f** [comment]
Maybe it didn't load add-on correctly 🔒

**Comment by Sostay** [comment]
> Maybe it didn't load add-on correctly 🔒

The same thing happened after I updated Blender and the plugins…

![image](https://github.com/mika-f/blender-drag-and-drop/assets/6897274/0379cac9-db44-4cce-a31e-89bbc610c74f)

![image](https://github.com/mika-f/blender-drag-and-drop/assets/6897274/c73f009e-1674-4e8c-bbc6-a8f2f08eaf36)

**Comment by Sostay** [comment]
btw, i'm using the Portable version

**Comment by mika-f** [comment]
Thank you for your detail information. I will support to Blender 3.6.5 in few days.
