### ISSUE TITLE
[Bug]: Version 3.6.2 doesn‘t work, 3.6.1 was fine.

### ISSUE THREAD

**Issue by dkpress** [mika-f/blender-drag-and-drop#57]
### What happened?

My Blender version is 3.6.2, When I drag in an .lbj file, nothing happens. but it was OK in 3.6.1

Hope you can check it out when you have time, thank you very much!

### Add-on Version

2.8.0

**Comment by mika-f** [comment]
I realized today that the code for Blender 3.6.2 is included, but not released... :P
I will released it as v2.9 in today.

**Comment by mika-f** [comment]
I just released v2.9.0, it supports Blender 3.6.2.
https://github.com/mika-f/blender-drag-and-drop/releases/tag/v2.9.0

**Comment by dkpress** [comment]
Thank you very much！

**Comment by dkpress** [comment]
> I realized today that the code for Blender 3.6.2 is included, but not released... :P I will released it as v2.9 in today.
> 
> 
> 我今天意识到Blender 3.6.2的代码包含在内，但没有发布。：P 今天我将把它作为v2.9发布。



> I realized today that the code for Blender 3.6.2 is included, but not released... :P I will released it as v2.9 in today.

Thank you very much！

**Comment by dkpress** [comment]
> I realized today that the code for Blender 3.6.2 is included, but not released... :P I will released it as v2.9 in today.

Thank you very much！
