### ISSUE TITLE
[Feature Request]: Support to Blender 4.0.0

### ISSUE THREAD

**Issue by mika-f** [mika-f/blender-drag-and-drop#67]
### What do you want?

If Blender 4.x does not supports to import file(s) via Drag and Drop, I'll support this add-on for Blender 4.x.

### Blender versions

edge

**Comment by takiyao** [comment]
I can corroborate that indeed it doesn't work on 4.0

**Comment by mika-f** [comment]
I merged related PR. It will be released today or tomorrow.
