### ISSUE TITLE
[Bug]: Blender LTS 3.6 STL/PLY no action

### ISSUE THREAD

**Issue by SunDude** [mika-f/blender-drag-and-drop#93]
### What happened?

No pop-up or any action happens when dragging and dropping a stl/ply file, is 3.6 LTS not supported?

### Add-on Version

2.12.1

### Blender versions

3.6 LTS

**Comment by mika-f** [comment]
Can you provide patch version of Blender?
This refers to part _**2**_ of 3.6.2. Maybe you are using Blender 3.6.7, 3.6.8, or 3.6.9.

If that's the case, I'll fix in this week or next week.

**Comment by SunDude** [comment]
This occurs on blender 3.6.8, I hadn't realised there was a number after the first 2 and I can see this version are not currently supported. I'll close this as it's working as intended at the moment. My apologies.
